version: "3.8"
services:
  db:
    image: mysql:8.0
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ''
    volumes:
      - mysql-db:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
  api:
    build:
      context: ./api
      dockerfile: docker/Dockerfile
    container_name: api
    volumes:
      - ./api:/api
    ports:
      - "3000:3000"
    environment:
      MYSQL_HOST: 'db'
      MYSQL_PORT: 3306
    depends_on:
      - db
    tty: true

volumes:
  mysql-db:
    driver: local

