version: "3.8"
services:
  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: ${API_DATABASE_USER}
      MYSQL_PASSWORD: ${API_DATABASE_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
  api:
    build:
      context: ./api
      dockerfile: docker/Dockerfile
    volumes:
      - ./api:/api
      - bundle-data:/api/vendor/bundle
      - tmp-data:/api/tmp
      - log-data:/api/log
    environment:
      MYSQL_HOST: 'db'
      MYSQL_PORT: 3306
      RAILS_ENV: 'production'
    env_file: .env
    command: "bin/rails s"
    depends_on:
      - db
  nginx:
    image: nginx:1.19.8
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - tmp-data:/api/tmp
    ports:
      - 80:80
    depends_on:
      - api

volumes:
  tmp-data:
  log-data:
