version: "3.8"
services:
  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_RANDOM_ROOT_PASSWORD: ''
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - dev-mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
  api:
    build:
      context: ./api
      dockerfile: docker/Dockerfile
    volumes:
      - ./api:/api
      - dev-bundle-data:/api/vendor/bundle
    ports:
      - 3000:3000
    environment:
      MYSQL_HOST: 'db'
      MYSQL_PORT: 3306
    command: "bin/rails s -b 0.0.0.0"
    depends_on:
      - db
    tty: true

volumes:
  dev-mysql-data:
  dev-bundle-data:
