version: "3.8"
services:
  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_RANDOM_ROOT_PASSWORD: ''
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
  api:
    build:
      context: ./api
      dockerfile: docker/Dockerfile
    volumes:
      - ./api:/api
      - log-data:/api/log
      - bundle-data:/api/vendor/bundle
    ports:
      - 3000:3000
    environment:
      MYSQL_HOST: 'db'
      MYSQL_PORT: 3306
    command: "bin/rails s -e production"
    depends_on:
      - db
    tty: true
  nginx:
    image: nginx:1.19.8
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 80:80
    depends_on:
      - api

volumes:
  mysql-data:
  log-data:
  bundle-data:
