version: "3.8"
services:
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_RANDOM_ROOT_PASSWORD: ''
    volumes:
      - mysql-db:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
  api:
    build:
      context: ./api
      dockerfile: docker/Dockerfile
    volumes:
      - ./api:/api
    ports:
      - "3000:3000"
    environment:
      MYSQL_HOST: 'db'
      MYSQL_PORT: 3306
    command: "bin/rails s -b 0.0.0.0"
    depends_on:
      - db
    tty: true
  nginx:
    image: nginx:1.19.8
    ports:
      - "80:80"

volumes:
  mysql-db:
    driver: local

