FROM ruby:2.7.1-slim-buster as build

RUN apt-get update \
  && apt-get install -y default-mysql-client \
  libmariadb-dev \
  build-essential \
  --no-install-recommends \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /api

COPY Gemfile Gemfile.lock ./
RUN bundle config set path vendor/bundle
RUN bundle install

ENTRYPOINT ["docker/entrypoint.sh"]
CMD ["bin/rails", "s"]

