default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  host: <%= ENV.fetch("MYSQL_HOST") { "localhost" } %>
  port: <%= ENV.fetch("MYSQL_POST") { 3306 } %>


development:
  <<: *default
  database: api_development

test:
  <<: *default
  database: api_test

production:
  <<: *default
  database: api_production
  username: <%= ENV.fetch("API_DATABASE_USER") %>
  password: <%= ENV.fetch("API_DATABASE_PASSWORD") %>
